name: Node.js CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
        working-directory: ./node/express-prisma-typescript
      - run: yarn build
        working-directory: ./node/express-prisma-typescript
      - run: yarn test
        working-directory: ./node/express-prisma-typescript
